name: Build Android Kotlin
on: [push,pull_request,workflow_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        
      - name: Setup Ninja 
        uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
          
      - name: Set up cache
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ${{ github.workspace }}/.ccache
          key: ${{ runner.os }}-android-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-
            
      - name: Build Release apk
        run: |
          export NDK_CCACHE=$(which ccache)
          cd tools/android_project_kotlin/
          chmod +x ./gradlew && ./gradlew assembleRelease
          ls app/build/outputs/apk/release/
          ccache -s -v
          
      - name: GH Release 🚀
        # You may pin to the exact commit or the version.
        uses: actions/upload-artifact@v4
        with:
           name: AndroidRelease
           path: tools/android_project_kotlin/app/build/outputs/apk/release/com.sky.SkyEmu-*-release.apk
        
 
